Trying to learn how to use PyCUDA...

Gonna start off with comparing serial vs parrallized mandelbrot.

In [10]:
# Used example code online to just get the libraries working, Windows PATH variables are annoying...

import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule

import numpy
a = numpy.random.randn(4,4)
a = a.astype(numpy.float32)
a_gpu = cuda.mem_alloc(a.nbytes)
cuda.memcpy_htod(a_gpu, a)
mod = SourceModule("""
  __global__ void doublify(float *a)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] *= 2;
  }
  """)

a_doubled = numpy.empty_like(a)
cuda.memcpy_dtoh(a_doubled, a_gpu)
print(a_doubled)
print(a)

[[ 2.45485    -1.1485823   0.7697816  -0.6936119 ]
 [-0.6890353  -0.8065086   0.05871063  0.05045864]
 [ 0.5774545   1.1132321  -0.18662958 -0.5588438 ]
 [ 0.03573484  1.6901095  -3.0229142   0.11931873]]
[[ 2.45485    -1.1485823   0.7697816  -0.6936119 ]
 [-0.6890353  -0.8065086   0.05871063  0.05045864]
 [ 0.5774545   1.1132321  -0.18662958 -0.5588438 ]
 [ 0.03573484  1.6901095  -3.0229142   0.11931873]]
